### ISSUE TITLE
concatenation necessary?

### ISSUE THREAD

**Issue by rdewijn** [tercen/anova1_operator#4]
This statement is presumably used to concatenate colors, if multiple:

(line 30)  
`mutate(.group.colors = do.call(function(...) paste(..., sep='.'), ctx$select(ctx$colors)))`

but is that necessary given line 24:

`if (length(ctx$colors) != 1) stop("Grouping for ANOVA1 must be defined using exactly one data color.")`

Remove either one?

**Comment by ginberg** [comment]
I have removed the paste since it's not needed
